# Generated by Django 5.0.6 on 2024-08-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Wizard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.DateTimeField(null=True),
        ),
    ]
