# Generated by Django 5.1 on 2024-08-20 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wizard', '0002_user_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('priority', models.CharField(max_length=50)),
                ('code', models.IntegerField()),
                ('log_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='Wizard.logfiles')),
            ],
        ),
        migrations.DeleteModel(
            name='Errors',
        ),
    ]
