# Generated by Django 5.0.6 on 2024-08-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Wizard", "0004_logs_os_logs_browser"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                max_length=1,
                null=True,
            ),
        ),
    ]
